### ISSUE TITLE
An error occurred when creating an account

### ISSUE THREAD

**Issue by SakiTakamachi** [php/web-wiki#22]
Messages similar to the following was displayed:

```
There was an unexpected problem communicating with SMTP: Start TLS failed to enable crypto
```

```
Looks like there was an error on sending the password mail. Please contact the admin!
```

Maybe it's because of what happened a few days ago? It seems like my account was created half-heartedly, what should I do in this case?

**Comment by Girgias** [comment]
I've asked @derickr to have a look at this.

**Comment by SakiTakamachi** [comment]
Thank you!

**Comment by derickr** [comment]
The sending of emails should now work again. The SSL certificate was expired, and had not been reconfigured for Let's Encrypt yet. I have done that now.

**Comment by SakiTakamachi** [comment]
@derickr 

Thank you.

However, it seems that the account has been incompletely created, and the account name you previously entered cannot be used.

```
The user could not be created.
```

**Comment by derickr** [comment]
Oh, let's see if I can fix that.

**Comment by derickr** [comment]
I see there are two with "saki". One with, and one without second name. I can delete them both, so you can retry?

**Comment by SakiTakamachi** [comment]
@derickr 

Thank you! I will recreate it, so feel free to delete both.

**Comment by derickr** [comment]
Done.

**Comment by SakiTakamachi** [comment]
Thank you! I was able to register!
